### ISSUE TITLE
Create permissions in Cluster Role for cloudability-agent

### ISSUE THREAD

**Issue by satyamag** [cloudability/metrics-agent#124]
The kubernetes manifest created post provisioning a cluster via cloudability console requires the following permissions in the ClusterRole

```yaml
- apiGroups: [""]
  resources:
    - "services/proxy"
    - "pods/proxy"
    - "nodes/proxy"
    - "nodes/stats"
    - "nodes/metrics"
  verbs:
    - "get"
    - "list"
    - "create"
```

Can you please help us understand why the `create` permission is required. Pointers to the code where the create permissions are used would be very helpful.
