### ISSUE TITLE
Allow Volumes and VolumeMounts to be added via Helm

### ISSUE THREAD

**Issue by cloudpea** [cloudability/metrics-agent#213]
We would like to add additional volumes and volume mounts via the metrics-agent Helm chart so we can inject the API token via Secrets Store CSI Driver.

The below additional values would allow us to configure this.

```
additionalVolumeMounts:
  - name: secrets-store-cloudability
     mountPath: "/mnt/secrets-store-cloudability"
     readOnly: true

additionalVolumes:
  - name: secrets-store-cloudability
    csi:
      driver: secrets-store.csi.k8s.io
      readOnly: true
      volumeAttributes:
        secretProviderClass: csi-cloudability-secret
```
